// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/notas-fiscais": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Notas Fiscais"
                ],
                "summary": "Lista notas fiscais",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "Pagina",
                        "name": "pagina",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 20,
                        "description": "Itens por pagina (maximo 100)",
                        "name": "tamanhoPagina",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Numero exato da nota",
                        "name": "numero",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "ABERTA",
                            "PROCESSANDO",
                            "FECHADA"
                        ],
                        "type": "string",
                        "description": "Status da nota",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Trecho do nome do cliente",
                        "name": "nomeCliente",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.SuccessResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dto.NotasFiscaisPaginadasResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Notas Fiscais"
                ],
                "summary": "Cria uma nota fiscal",
                "parameters": [
                    {
                        "description": "Dados da nota",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.CriarNotaFiscalRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.SuccessResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dto.NotaFiscalResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/notas-fiscais/{id}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Notas Fiscais"
                ],
                "summary": "Consulta uma nota fiscal",
                "parameters": [
                    {
                        "type": "string",
                        "description": "UUID da nota",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.SuccessResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dto.NotaFiscalResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "description": "Substitui cliente, endereco e itens. A operacao e permitida somente no status ABERTA.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Notas Fiscais"
                ],
                "summary": "Atualiza uma nota fiscal aberta",
                "parameters": [
                    {
                        "type": "string",
                        "description": "UUID da nota",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Novos dados da nota",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.AtualizarNotaFiscalRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.SuccessResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dto.NotaFiscalResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/notas-fiscais/{id}/fechamento": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Notas Fiscais"
                ],
                "summary": "Inicia o fechamento de uma nota fiscal",
                "parameters": [
                    {
                        "type": "string",
                        "description": "UUID da nota",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.SuccessResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dto.NotaFiscalResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "dto.AtualizarNotaFiscalRequest": {
            "type": "object",
            "required": [
                "enderecoCliente",
                "itens",
                "nomeCliente"
            ],
            "properties": {
                "enderecoCliente": {
                    "type": "string",
                    "example": "AVENIDA BRASIL, 200 - CURITIBA/PR"
                },
                "itens": {
                    "type": "array",
                    "minItems": 1,
                    "items": {
                        "$ref": "#/definitions/dto.CriarNotaFiscalItemRequest"
                    }
                },
                "nomeCliente": {
                    "type": "string",
                    "example": "MARIA DA SILVA"
                }
            }
        },
        "dto.CriarNotaFiscalItemRequest": {
            "type": "object",
            "required": [
                "codigoProduto",
                "quantidade"
            ],
            "properties": {
                "codigoProduto": {
                    "type": "string",
                    "example": "SKU-001"
                },
                "quantidade": {
                    "type": "integer",
                    "example": 2
                }
            }
        },
        "dto.CriarNotaFiscalRequest": {
            "type": "object",
            "required": [
                "enderecoCliente",
                "itens",
                "nomeCliente"
            ],
            "properties": {
                "enderecoCliente": {
                    "type": "string",
                    "example": "RUA DAS FLORES, 100 - CURITIBA/PR"
                },
                "itens": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.CriarNotaFiscalItemRequest"
                    }
                },
                "nomeCliente": {
                    "type": "string",
                    "example": "MARIA DA SILVA"
                }
            }
        },
        "dto.ItemNotaFiscalResponse": {
            "type": "object",
            "properties": {
                "codigoProduto": {
                    "type": "string",
                    "example": "SKU-001"
                },
                "descricaoProduto": {
                    "type": "string",
                    "example": "TECLADO MECANICO"
                },
                "id": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440001"
                },
                "produtoId": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440002"
                },
                "quantidade": {
                    "type": "integer",
                    "example": 2
                },
                "valor": {
                    "type": "number",
                    "example": 159.9
                },
                "valorTotal": {
                    "type": "number",
                    "example": 319.8
                }
            }
        },
        "dto.NotaFiscalResponse": {
            "type": "object",
            "properties": {
                "dataAtualizacao": {
                    "type": "string",
                    "example": "2026-08-23T12:00:00Z"
                },
                "dataCadastro": {
                    "type": "string",
                    "example": "2026-08-23T12:00:00Z"
                },
                "dataFechamento": {
                    "type": "string",
                    "example": "2026-08-23T12:05:00Z"
                },
                "enderecoCliente": {
                    "type": "string",
                    "example": "RUA DAS FLORES, 100 - CURITIBA/PR"
                },
                "id": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                },
                "itens": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.ItemNotaFiscalResponse"
                    }
                },
                "nomeCliente": {
                    "type": "string",
                    "example": "MARIA DA SILVA"
                },
                "numero": {
                    "type": "integer",
                    "example": 1001
                },
                "quantidadeTotal": {
                    "type": "integer",
                    "example": 2
                },
                "status": {
                    "type": "string",
                    "enum": [
                        "ABERTA",
                        "PROCESSANDO",
                        "FECHADA"
                    ],
                    "example": "ABERTA"
                },
                "valorTotal": {
                    "type": "number",
                    "example": 319.8
                }
            }
        },
        "dto.NotasFiscaisPaginadasResponse": {
            "type": "object",
            "properties": {
                "itens": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.NotaFiscalResponse"
                    }
                },
                "pagina": {
                    "type": "integer",
                    "example": 1
                },
                "tamanhoPagina": {
                    "type": "integer",
                    "example": 20
                },
                "total": {
                    "type": "integer",
                    "example": 42
                },
                "totalPaginas": {
                    "type": "integer",
                    "example": 3
                }
            }
        },
        "response.ErrorData": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "response.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "$ref": "#/definitions/response.ErrorData"
                },
                "success": {
                    "type": "boolean",
                    "example": false
                }
            }
        },
        "response.SuccessResponse": {
            "type": "object",
            "properties": {
                "data": {},
                "success": {
                    "type": "boolean",
                    "example": true
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Faturamento Service API",
	Description:      "API do contexto de Faturamento do Sistema de Emissao de Notas Fiscais.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
